# Application name
spring.application.name=backend

# --- PostgreSQL Configuration ---
spring.datasource.url=jdbc:postgresql://localhost:5432/core_framework
spring.datasource.username=ny_haritina
spring.datasource.password=nh20041010
spring.datasource.driver-class-name=org.postgresql.Driver

# --- JPA / Hibernate Configuration ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# --- Devtools Auto-restart ---
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true